name: "Validate Firewall Rules CSV"
description: "Validate firewall_rules.csv format and rules."
inputs:
  input-file:
    description: "Path to the firewall_rules.csv"
    required: true
outputs:
  result:
    description: "Validation result output"
    value: ${{ steps.run_validation.outputs.result }}
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - name: Run validation script
      id: run_validation
      run: |
        set -o pipefail
        python ${{ github.action_path }}/validate.py --input-file "${{ inputs.input-file }}" > validation_output.txt || true
        cat validation_output.txt
        echo "result<<EOF" >> $GITHUB_OUTPUT
        cat validation_output.txt >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        grep -q "Error:" validation_output.txt && exit 1
      shell: bash
