name: "Convert Firewall Rules CSV to JSON"
description: "Converts firewall_rules.csv to structured JSON security group files."
inputs:
  input-file:
    description: "Path to the firewall_rules.csv"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - name: Run validation script
      id: run_validation
      shell: bash
      run: |
            set -o pipefail
            python ${{ github.action_path }}/validate.py --input-file "${{ inputs.input-file }}" > validation_output.txt || true

            echo "::group::Validation Output"
            cat validation_output.txt
            echo "::endgroup::"

            # Export result for GitHub Actions
            echo "result<<EOF" >> $GITHUB_OUTPUT
            cat validation_output.txt >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT

            # Fail the step if validation errors are found
            if grep -q "Error:" validation_output.txt; then
              exit 1
            fi
    
    - name: Run conversion script
      run: |
        python ${{ github.action_path }}/convert.py --input-file ${{ inputs.input-file }}
      shell: bash