name: Handle Closed PR for Firewall Rules

on:
  pull_request:
    types: [closed]

jobs:
  handle_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
    steps:
      - name: Comment and Update Related Issue
        run: |
          ISSUE_NUMBER=$(echo "${{ github.event.pull_request.head.ref }}" | grep -o '[0-9]*')
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"

          if [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
            gh issue close "$ISSUE_NUMBER" --comment "This issue was automatically closed because the PR #${{ github.event.pull_request.number }} was merged."
          else
            gh issue comment "$ISSUE_NUMBER" --body "The PR #${{ github.event.pull_request.number }} was closed without merging. Please resubmit by editing the issue or opening a new one."
            gh issue edit "$ISSUE_NUMBER" --add-label "rejected"
          fi

          # Always try to delete branch if not main
          if [[ "$BRANCH_NAME" != "main" && "$BRANCH_NAME" != "master" ]]; then
            git push origin --delete "$BRANCH_NAME"
          fi
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB_ACTIONS }}