name: "Check duplicates and merge existing"
description: "Check for duplicates within and between existing policy and merge if necessary"
inputs:
  created_yaml:
    description: "list of request yaml(s)"
    required: true
  request_existing_mapping:
    description: "request/existing policy mapping"
    required: true

outputs:
  pretty_message:
    description: 'Pretty, markdown-formatted duplicate detection message'
    value: ${{ steps.find_duplicates.outputs.pretty_message }}
  duplicates_detected:
    description: 'True if duplicates found'
    value: ${{ steps.find_duplicates.outputs.duplicates_detected }}
  validated_policy_filenames:
    description: "Space-separated list of filenames that passed validation"
    value: ${{ steps.find_duplicates.outputs.validated_policy_filenames }}

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        clean: false
    
    - name: Install deps
      run: |
        python -m pip install -r ${{github.action_path}}/requirements.txt
      shell: bash
    

    - name: Check for duplicates
      id: find_duplicates
      shell: bash
      run: |
        set -e
        rm -f validated_filenames.txt
        status=0
        MAPPING=$(echo "${{ inputs.request_existing_mapping }}" | tr '|' '\n')
        if [[ -z "$MAPPING" ]]; then
          echo "No mapping provided, nothing to validate."
          exit 0
        fi

        while IFS=, read -r request_file existing_file; do
          if [[ -n "$existing_file" ]]; then
            python yaml-duplicate-validator.py "$request_file" "$existing_file"
          else
            python yaml-duplicate-validator.py "$request_file"
          fi
        done <<< "$MAPPING"

        # Space-separated filenames for output
        outfiles=$(awk '{print $2}' validated_filenames.txt | tr '\n' ' ')
        echo "pretty_message<<EOF" >> $GITHUB_OUTPUT
        cat dupe_output.txt >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        echo "duplicates_detected=$([ $status -eq 1 ] && echo true || echo false)" >> $GITHUB_OUTPUT
        echo "validated_policy_filenames=$outfiles" >> $GITHUB_OUTPUT
        exit $status
