name: "Check duplicates and merge existing"
description: "Check for duplicates within and between existing policy and merge if necessary"
inputs:
  created_yaml:
    description: "current issue payload"
    required: true
  token:
    description: 'github pat'
    required: true
  repo:
    description: 'github repository'
    required: true

outputs:
  pretty_message:
    description: 'Pretty, markdown-formatted duplicate detection message'
    value: ${{ steps.find_duplicates.outputs.pretty_message }}
  duplicates_detected:
    description: 'True if duplicates found'
    value: ${{ steps.find_duplicates.outputs.duplicates_detected }}

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        clean: false
    
    - name: Get existing policy files to check against new request yaml
      shell: bash
      run: |
        policies_folder=$(curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.token }}" \
          https://api.github.com/repos/${{ inputs.repo }}/contents/policies)
        echo "$policies_folder" | jq -r '.[].name' > policies.txt

    - name: Install deps
      run: |
        python -m pip install -r ${{github.action_path}}/requirements.txt
      shell: bash
    
    - name: Check for duplicates
      env: 
        created_yaml: ${{ inputs.created_yaml }}
        token: ${{ inputs.token }}
        repo: ${{ inputs.repo }}
      id: find_duplicates
      shell: bash
      run: |
        set +e
        python ${{github.action_path}}/yaml-duplicate-validator.py > dupe_output.txt 2>&1
        STATUS=$?
        cat dupe_output.txt
        # Emit output for use by workflow
        echo "pretty_message<<EOF" >> $GITHUB_OUTPUT
        cat dupe_output.txt >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        echo "duplicates_detected=$([ $STATUS -eq 1 ] && echo true || echo false)" >> $GITHUB_OUTPUT
        exit $STATUS
