name: Firewall Rule Issue Workflow

on:
  issues:
    types: [opened]

jobs:
  process_issue:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract CSV, append, commit changes, and create PR
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
          GH_TOKEN: ${{ secrets.PAT_GITHUB_ACTIONS }}
        run: |
          # Extract CSV from issue body
          echo "$ISSUE_BODY" | sed -n '/RequestID,name,security_group_id/,$p' > new_rule.csv
          tail -n +2 new_rule.csv >> firewall_rules.csv
          rm new_rule.csv

          # Commit changes explicitly
          BRANCH_NAME="firewall-rule-${{ github.event.issue.number }}"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout -b $BRANCH_NAME
          git add firewall_rules.csv
          git commit -m "Add firewall rule from issue #${{ github.event.issue.number }}"
          git push -u origin $BRANCH_NAME

          # Create Pull Request using official GitHub CLI
          gh pr create \
            --title "Firewall Rule Request from Issue #${{ github.event.issue.number }}" \
            --body "This PR was automatically generated from issue #${{ github.event.issue.number }}.\n\nPlease review and merge." \
            --base main \
            --head $BRANCH_NAME