name: Update v1 Tag

on:
  release:
    types:
      - published


jobs:
  update-v1-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Move v1 tag to latest release
        run: |
          git fetch --tags
          git tag -f v1 ${{ github.event.release.tag_name }}
          git push origin v1 --force
